"use client";

import { TRACK_COLS, TRACK_NAMES, type TrackKey } from "@/lib/constants";

interface Props {
  allYears: string[];
  selectedYears: string[];
  onYearsChange: (y: string[]) => void;
  selectedTracks: string[];
  onTracksChange: (t: string[]) => void;
  useMock: boolean;
}

export default function Sidebar({
  allYears,
  selectedYears,
  onYearsChange,
  selectedTracks,
  onTracksChange,
  useMock,
}: Props) {
  const toggleYear = (y: string) => {
    onYearsChange(
      selectedYears.includes(y)
        ? selectedYears.filter((v) => v !== y)
        : [...selectedYears, y].sort()
    );
  };
  const toggleTrack = (t: string) => {
    onTracksChange(
      selectedTracks.includes(t)
        ? selectedTracks.filter((v) => v !== t)
        : [...selectedTracks, t]
    );
  };

  return (
    <aside className="w-64 min-h-screen bg-sidebar-bg text-sidebar-text flex flex-col p-5 shrink-0">
      <h1 className="text-xl font-bold text-sidebar-heading mb-0.5">
        EIL Dashboard
      </h1>
      <p className="text-xs text-sidebar-muted mb-4 leading-relaxed">
        English as an International Language
        <br />
        Chulalongkorn University
      </p>

      <hr className="border-sidebar-divider mb-4" />

      {useMock && (
        <div className="bg-sidebar-alert border border-sidebar-alert-border rounded-md px-3 py-2 text-xs text-sidebar-muted mb-4">
          Showing mock preview data. Connect Supabase or run the extraction
          pipeline to load real results.
        </div>
      )}

      {/* ── Year filter ────────────────────────────────────── */}
      <h3 className="text-xs font-semibold uppercase tracking-wider text-sidebar-muted mb-2">
        Filter by Year
      </h3>
      <div className="max-h-52 overflow-y-auto space-y-1 mb-4 pr-1">
        <button
          className="text-[11px] text-blue-300 hover:underline mb-1"
          onClick={() =>
            onYearsChange(
              selectedYears.length === allYears.length ? [] : [...allYears]
            )
          }
        >
          {selectedYears.length === allYears.length
            ? "Deselect all"
            : "Select all"}
        </button>
        {allYears.map((y) => (
          <label
            key={y}
            className="flex items-center gap-2 cursor-pointer text-sm"
          >
            <input
              type="checkbox"
              checked={selectedYears.includes(y)}
              onChange={() => toggleYear(y)}
              className="rounded border-sidebar-divider text-blue-500 focus:ring-blue-500/30"
            />
            {y}
          </label>
        ))}
      </div>

      {/* ── Track filter ───────────────────────────────────── */}
      <h3 className="text-xs font-semibold uppercase tracking-wider text-sidebar-muted mb-2">
        Filter by Track
      </h3>
      <div className="space-y-1 mb-4">
        {TRACK_COLS.map((t) => (
          <label
            key={t}
            className="flex items-center gap-2 cursor-pointer text-sm"
          >
            <input
              type="checkbox"
              checked={selectedTracks.includes(t)}
              onChange={() => toggleTrack(t)}
              className="rounded border-sidebar-divider text-blue-500 focus:ring-blue-500/30"
            />
            <span>
              {t}{" "}
              <span className="text-sidebar-muted text-xs">
                — {TRACK_NAMES[t as TrackKey]}
              </span>
            </span>
          </label>
        ))}
      </div>

      <hr className="border-sidebar-divider my-3" />

      <p className="text-[11px] text-sidebar-muted leading-relaxed mt-auto">
        <strong>Data source:</strong> CSV files generated by the EIL LLM
        extraction pipeline, stored in Supabase.
      </p>
    </aside>
  );
}
